meta_product_name: "Movie"
meta_title: "Perfect Watch"
meta_description: "Find a movie in 5 minutes!"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
