meta_product_name: "Movie"
meta_title: "Perfect Watch"
meta_description: "Perfect Watch - Find a movie in 5 minutes!"
meta_image: "" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
